<?xml version="1.0"?>
<suiteResults>
  <FitNesseVersion>v20200501</FitNesseVersion>
  <rootPath>FrontPage.fitnessetest.SuitePage</rootPath>
  <executionLog>
    <testSystem>fit:fit.FitServer</testSystem>
    <command>java -cp C:\Fitnesse\fitnesse-standalone.jar fit.FitServer murex-lap10 58938 3863</command>
    <exitCode>1</exitCode>
    <stdOut></stdOut>
    <stdErr>Exception in thread "main" java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.&lt;init&gt;(Unknown Source)
	at java.net.Socket.&lt;init&gt;(Unknown Source)
	at fit.FitServer.establishConnection(FitServer.java:150)
	at fit.FitServer.establishConnection(FitServer.java:146)
	at fit.FitServer.run(FitServer.java:54)
	at fit.FitServer.main(FitServer.java:41)
</stdErr>
    <exception>FitClient external process terminated before a connection could be established</exception>
    <exception>FitClient external process terminated before a connection could be established</exception>
  </executionLog>
  <finalCounts>
    <right>0</right>
    <wrong>0</wrong>
    <ignores>0</ignores>
    <exceptions>1</exceptions>
  </finalCounts>
  <totalRunTimeInMillis>1026</totalRunTimeInMillis>
</suiteResults>

